# Generated by Django 3.2.9 on 2021-12-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog_site_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.authors'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.posts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.authors'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.authors'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_blog_site_api.categories'),
        ),
    ]
