# Generated by Django 3.2.9 on 2021-12-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog_site_api', '0002_auto_20211216_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
