# Generated by Django 3.2.9 on 2021-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog_site_api', '0003_alter_authors_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='bio',
            field=models.TextField(),
        ),
    ]
