# Generated by Django 3.2.9 on 2021-12-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_blog_site_api', '0004_alter_authors_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(),
        ),
    ]
